spring.application.name=licensing-compliance-service

# Data Source
spring.datasource.url=jdbc:postgresql://localhost:5432/licensing_service?stringtype=unspecified
spring.datasource.username=license_app
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=INFO
logging.level.org.hibernate.SQL=WARN

jwt.secret=K8l9eV8mQ2xKNiX3T1uWc8RbHs3Jd6ZaXv0LgBnCyEk=

# 10 min
jwt.access-token-expiration=600000 

# 7 days
jwt.refresh-token-expiration=604800000

