spring.application.name=licensing-compliance-service

spring.config.import=optional:dotenv:.env
# Data Source
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=INFO
logging.level.org.hibernate.SQL=WARN

jwt.secret=${JWT_SECRET:K8l9eV8mQ2xKNiX3T1uWc8RbHs3Jd6ZaXv0LgBnCyEk=}

# 10 min
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:600000}

# 7 days
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:604800000}


